#!/usr/bin/env python3

import argparse
import json
import os
import sys
from pathlib import Path


TUTORIAL_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = TUTORIAL_ROOT / "curriculum.json"
GENERATED_HEADER = "<!-- GENERATED by tools/generate_navigation.py. DO NOT EDIT. -->\n"


def load_manifest():
    with MANIFEST_PATH.open(encoding="utf-8") as stream:
        return json.load(stream)


def unit_link(unit, output_path):
    target = TUTORIAL_ROOT / unit["path"]
    if unit["status"] == "planned" and not target.exists():
        return f"{unit['title']} (`{unit['id']}`)"
    relative = os.path.relpath(target, output_path.parent)
    return f"[{unit['title']}]({Path(relative).as_posix()})"


def render_root(manifest):
    release = manifest["release"]
    stages = sorted(manifest["stages"], key=lambda item: item["order"])
    release_note = (
        "`verified` 表示全部登记单元已完成非作者走查；`coverage_complete=true` 表示 scoped handwritten inputs 都有 verified primary owner。"
        if release["status"] == "verified"
        else "`draft` 表示内容已落盘并通过机械检查，但尚未完成非作者走查，不能当作 verified 教学路径。"
    )
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# xv6 教程",
        "",
        "这是一套独立、循序渐进的 xv6 教程。教程直接追踪当前仓库源码和测试，但不依赖 `docs/xv6-riscv/`。",
        "",
        "## 当前发布版",
        "",
        f"- 版本：`{release['version']}`",
        f"- 状态：`{release['status']}`",
        f"- 源码基线：`{release['baseline_commit']}`",
        f"- 完整覆盖：`{str(release['coverage_complete']).lower()}`",
        "",
        release_note,
        "",
        "## 从这里开始",
        "",
        "- 零先修学习者：从[基础路径](foundation/README.md)开始，完成 Foundation gate 后进入核心路径。",
        "- 已具备基础者：先完成 Foundation gate；通过后进入同一条[核心路径](core/README.md)。",
        "- 问题驱动复核：使用教程内的[权威问题集](questions/README.md)；`docs/questions/` 只保留兼容入口。",
        "- 查看整体建设状态：[阶段索引](stages/README.md)。",
        "",
        "## 建设约束",
        "",
        "完整建设范围见 [`spec.md`](spec.md)，统一术语见 [`CONTEXT.md`](CONTEXT.md)，访谈形成的架构决策保存在 [`adr/`](adr/)，Agent 发现规则见 [`AGENTS.md`](AGENTS.md)。这些材料都属于这个独立教程目录。",
        "",
        "## 阶段",
        "",
        "| 顺序 | 阶段 | 类型 |",
        "|---:|---|---|",
    ]
    for stage in stages:
        lines.append(f"| {stage['order']} | {stage['title']} (`{stage['id']}`) | {stage['kind']} |")
    lines.extend([
        "",
        "## 教程工具",
        "",
        "```sh",
        "python3 docs/xv6-tutorial/tools/validate.py",
        "python3 docs/xv6-tutorial/tools/generate_navigation.py --check",
        "```",
        "",
        "单元作者从 [`templates/unit.md`](templates/unit.md) 开始；学习者可复制 [`templates/trace-worksheet.md`](templates/trace-worksheet.md) 记录追踪证据。",
        "",
    ])
    return "\n".join(lines)


def render_foundation(manifest, output_path):
    units = sorted(
        (unit for unit in manifest["units"] if unit["stage"] == "foundation"),
        key=lambda item: item["order"],
    )
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# 基础路径",
        "",
        "基础路径不假定读者已经会 C、命令行、RISC-V 或 GDB。每个单元都产生可检查的出口产物，最终由 Foundation gate 判断是否可以进入核心路径。",
        "",
        "| 顺序 | 单元 | 状态 |",
        "|---:|---|---|",
    ]
    for unit in units:
        lines.append(f"| {unit['order']} | {unit_link(unit, output_path)} | `{unit['status']}` |")
    lines.append("")
    return "\n".join(lines)


def render_core(manifest, output_path):
    stages = sorted(
        (stage for stage in manifest["stages"] if stage["kind"] == "core"),
        key=lambda item: item["order"],
    )
    units_by_stage = {}
    for unit in manifest["units"]:
        units_by_stage.setdefault(unit["stage"], []).append(unit)
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# 核心路径",
        "",
        "核心路径在七个螺旋阶段中反复回到真实行为。早期单元会明确留下黑盒，后续单元负责解除；显示顺序来自 `curriculum.json`，不是文件名。",
        "",
    ]
    for stage in stages:
        lines.extend([f"## {stage['title']}", ""])
        units = sorted(units_by_stage.get(stage["id"], []), key=lambda item: item["order"])
        if not units:
            lines.extend(["尚无已登记单元。", ""])
            continue
        for unit in units:
            lines.append(f"- {unit_link(unit, output_path)} - `{unit['status']}`")
        lines.append("")
    return "\n".join(lines)


def render_stages(manifest):
    stages = sorted(manifest["stages"], key=lambda item: item["order"])
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# 课程阶段索引",
        "",
        "| 阶段 | planned | draft | verified |",
        "|---|---:|---:|---:|",
    ]
    for stage in stages:
        counts = {status: 0 for status in ("planned", "draft", "verified")}
        for unit in manifest["units"]:
            if unit["stage"] == stage["id"]:
                counts[unit["status"]] += 1
        lines.append(
            f"| {stage['title']} (`{stage['id']}`) | {counts['planned']} | {counts['draft']} | {counts['verified']} |"
        )
    lines.extend([
        "",
        "只有满足技术发布门槛并完成非作者走查的单元才能标为 `verified`。",
        "",
    ])
    return "\n".join(lines)


def render_questions(manifest, output_path):
    stage_order = {stage["id"]: stage["order"] for stage in manifest["stages"]}
    entries = []
    for unit in manifest["units"]:
        for resource in unit["resources"]:
            if resource.startswith("questions/") and not resource.startswith("questions/answers/"):
                entries.append((stage_order[unit["stage"]], unit["order"], unit, resource))
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# xv6 教程权威问题集",
        "",
        "问题从真实控制流、状态、ownership、失败路径和证据边界生成；单元依赖与状态以 `curriculum.json` 为准。",
        "",
        "| 阶段顺序 | 单元 | 问题路径 | 状态 |",
        "|---:|---|---|---|",
    ]
    for stage, order, unit, resource in sorted(entries):
        target = TUTORIAL_ROOT / resource
        if unit["status"] == "planned" and not target.exists():
            question = f"{unit['title']} (`{resource}`)"
        else:
            relative = os.path.relpath(target, output_path.parent)
            question = f"[{unit['title']}]({Path(relative).as_posix()})"
        lines.append(
            f"| {stage}.{order} | `{unit['id']}` | {question} | `{unit['status']}` |"
        )
    lines.extend([
        "",
        "旧 `docs/questions/` 只保留指向本页的兼容入口，不维护同步副本。",
        "",
    ])
    return "\n".join(lines)


def expected_outputs(manifest):
    root_output = TUTORIAL_ROOT / "README.md"
    foundation_output = TUTORIAL_ROOT / "foundation" / "README.md"
    core_output = TUTORIAL_ROOT / "core" / "README.md"
    stages_output = TUTORIAL_ROOT / "stages" / "README.md"
    questions_output = TUTORIAL_ROOT / "questions" / "README.md"
    return {
        root_output: render_root(manifest),
        foundation_output: render_foundation(manifest, foundation_output),
        core_output: render_core(manifest, core_output),
        stages_output: render_stages(manifest),
        questions_output: render_questions(manifest, questions_output),
    }


def main():
    parser = argparse.ArgumentParser(description="Generate tutorial navigation from curriculum.json")
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    manifest = load_manifest()
    stale = []
    for path, content in expected_outputs(manifest).items():
        content = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(TUTORIAL_ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale generated navigation: {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
